global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['3.110.182.133:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['3.110.182.133:9100']

